[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "IPX"
authors = [{name = "Insu87", email = "stian@ipx.gg"}]
dynamic = ["version", "description"]
